/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 13 00:47:21 GMT 2022
 */

package org.remast.baralga.repository;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.Collection;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.TreeSet;
import java.util.Vector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.joda.time.DateTime;
import org.joda.time.DateTimeZone;
import org.joda.time.chrono.CopticChronology;
import org.junit.runner.RunWith;
import org.remast.baralga.repository.ActivityVO;
import org.remast.baralga.repository.BaralgaRestRepository;
import org.remast.baralga.repository.FilterVO;
import org.remast.baralga.repository.ProjectVO;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BaralgaRestRepository_ESTest extends BaralgaRestRepository_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("", "", "}}+gYQJ`KL");
      baralgaRestRepository0.initialize();
      JsonNode jsonNode0 = baralgaRestRepository0.readTreeFromJsonString("");
      assertTrue(jsonNode0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, (String) null, "");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.verifyLogin();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("", "", "}}+gYQJ`KL");
      ProjectVO projectVO0 = new ProjectVO("start", "", "", false);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.updateProject(projectVO0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, ":[l", "");
      ProjectVO projectVO0 = new ProjectVO("Values array must not be null", "Values array must not be null", "}X0)B}(qVmcyb<w", true);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.updateProject(projectVO0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, (String) null, "id");
      DateTimeZone dateTimeZone0 = DateTimeZone.getDefault();
      CopticChronology copticChronology0 = CopticChronology.getInstance(dateTimeZone0);
      DateTime dateTime0 = new DateTime((Object) null, copticChronology0);
      ProjectVO projectVO0 = new ProjectVO("org/joda/time/tz/data", "", "Mi4WSd~/7w~(F(8t`", false);
      ActivityVO activityVO0 = new ActivityVO(dateTime0, dateTime0, projectVO0);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.updateActivity(activityVO0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("8;iqWV", "8;iqWV", "");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.removeActivity((ActivityVO) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, "/k.CV*O'mLa'Mz~S9", "element");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.removeActivity((ActivityVO) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("s<?%i", (String) null, (String) null);
      LinkedHashSet<ActivityVO> linkedHashSet0 = new LinkedHashSet<ActivityVO>();
      linkedHashSet0.add((ActivityVO) null);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.removeActivities(linkedHashSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("", "", "");
      String string0 = "lmq(0q\\uMHG";
      ProjectVO projectVO0 = new ProjectVO("", string0, "3'/7]r", false);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.remove(projectVO0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, "com.fasterxml.jackson.core.JsonStreamContext", (String) null);
      ProjectVO projectVO0 = new ProjectVO("ocXZ.9Fxz_4g#6", (String) null, (String) null, true);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.remove(projectVO0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("project", "project", "lenient");
      baralgaRestRepository0.initialize();
      // Undeclared exception!
      try { 
        baralgaRestRepository0.readTreeFromJsonString("lenient");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'lenient': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: (String)\"lenient\"; line: 1, column: 8]
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("", "", "L/u?#T96b]");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.isProjectAdministrationAllowed();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, (String) null, (String) null);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.isProjectAdministrationAllowed();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, "riodFormat.weeks.list", "riodFormat.weeks.list");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.getAllProjects();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("u#rL?i3`H", "[N-", "u#rL?i3`H");
      FilterVO filterVO0 = new FilterVO();
      // Undeclared exception!
      try { 
        baralgaRestRepository0.getActivities(filterVO0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, (String) null, "");
      FilterVO filterVO0 = new FilterVO();
      // Undeclared exception!
      try { 
        baralgaRestRepository0.getActivities(filterVO0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("yyyy-MM-dd'T'HH:mm:ss", "yyyy-MM-dd'T'HH:mm:ss", "yyyy-MM-dd'T'HH:mm:ss");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.getActivities();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("", "", "");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.findProjectById("([a-zA-Z0-9-!#$%&'*+.^_`{|}~]+)/([a-zA-Z0-9-!#$%&'*+.^_`{|}~]+)");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, (String) null, "M:>");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.findProjectById((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, "Longest collision chain in symbol table (of size ", "= 1m(Ar'xz2=Oepk");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.addProjects((Collection<ProjectVO>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, "", "");
      ProjectVO projectVO0 = new ProjectVO("create", "", "create", false);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.addProject(projectVO0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("active", "active", "8S7l@LYe");
      ProjectVO projectVO0 = new ProjectVO("active", "", "XpY2Ff;ke4)P?k", true);
      ActivityVO activityVO0 = new ActivityVO((DateTime) null, (DateTime) null, projectVO0);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.addActivity(activityVO0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, "%|P", "SFxI+nGP");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.addActivity((ActivityVO) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, (String) null, "M:>");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.addActivities((Collection<ActivityVO>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, (String) null, (String) null);
      HashSet<ActivityVO> hashSet0 = new HashSet<ActivityVO>();
      hashSet0.add((ActivityVO) null);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.addActivities(hashSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("c0;~bL", "c0;~bL", "c0;~bL");
      baralgaRestRepository0.clearData();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("", "", "");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.readTreeFromJsonString("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("c0;~bL", "c0;~bL", "c0;~bL");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.verifyLogin();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("j,A5[Rg", "j,A5[Rg", "j,A5[Rg");
      baralgaRestRepository0.gatherStatistics();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, "riodFormat.weeks.list", "riodFormat.weeks.list");
      TreeSet<ActivityVO> treeSet0 = new TreeSet<ActivityVO>();
      Collection<ActivityVO> collection0 = baralgaRestRepository0.addActivities(treeSet0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("", "g", "");
      TreeSet<ProjectVO> treeSet0 = new TreeSet<ProjectVO>();
      baralgaRestRepository0.addProjects(treeSet0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("tqXm[E.", "tqXm[E.", "tqXm[E.");
      // Undeclared exception!
      try { 
        baralgaRestRepository0.getAllProjects();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, (String) null, (String) null);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.getActivities();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("blQye", "blQye", "blQye");
      ProjectVO projectVO0 = new ProjectVO("blQye", "blQye", "blQye", false);
      ActivityVO activityVO0 = new ActivityVO("blQye", (DateTime) null, (DateTime) null, "blQye", projectVO0);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.updateActivity(activityVO0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository((String) null, (String) null, (String) null);
      Vector<ActivityVO> vector0 = new Vector<ActivityVO>();
      baralgaRestRepository0.removeActivities(vector0);
      assertTrue(vector0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("tqXm[E.", "tqXm[E.", "tqXm[E.");
      baralgaRestRepository0.close();
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      BaralgaRestRepository baralgaRestRepository0 = new BaralgaRestRepository("", "", "");
      ProjectVO projectVO0 = new ProjectVO("", "", "", false);
      // Undeclared exception!
      try { 
        baralgaRestRepository0.addProject(projectVO0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.BaralgaRestRepository", e);
      }
  }
}
