/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 13 00:48:11 GMT 2022
 */

package org.remast.baralga.repository;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import okhttp3.Interceptor;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.remast.baralga.repository.GzipInterceptor;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GzipInterceptor_ESTest extends GzipInterceptor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GzipInterceptor gzipInterceptor0 = new GzipInterceptor();
      // Undeclared exception!
      try { 
        gzipInterceptor0.intercept((Interceptor.Chain) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.remast.baralga.repository.GzipInterceptor", e);
      }
  }
}
