/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 13 00:45:13 GMT 2022
 */

package org.remast.baralga.repository;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.joda.time.DateTimeZone;
import org.joda.time.Interval;
import org.joda.time.MutableDateTime;
import org.joda.time.Period;
import org.joda.time.PeriodType;
import org.joda.time.YearMonth;
import org.junit.runner.RunWith;
import org.remast.baralga.repository.FilterVO;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FilterVO_ESTest extends FilterVO_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FilterVO filterVO0 = new FilterVO();
      Interval interval0 = new Interval(0L, 0L);
      filterVO0.setTimeInterval(interval0);
      Interval interval1 = filterVO0.getTimeInterval();
      assertEquals(0L, interval1.getEndMillis());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FilterVO filterVO0 = new FilterVO();
      PeriodType periodType0 = PeriodType.yearWeekDayTime();
      Period period0 = new Period(0, 0, (-1400), 0, 7593750, 0, 0, 0, periodType0);
      MutableDateTime mutableDateTime0 = new MutableDateTime((-1266L));
      Interval interval0 = new Interval(period0, mutableDateTime0);
      filterVO0.setTimeInterval(interval0);
      Interval interval1 = filterVO0.getTimeInterval();
      assertEquals((-1266L), interval1.getEndMillis());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FilterVO filterVO0 = new FilterVO();
      DateTimeZone dateTimeZone0 = DateTimeZone.UTC;
      YearMonth yearMonth0 = new YearMonth(dateTimeZone0);
      Interval interval0 = yearMonth0.toInterval();
      filterVO0.setTimeInterval(interval0);
      Interval interval1 = filterVO0.getTimeInterval();
      assertEquals(1391223600000L, interval1.getStartMillis());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FilterVO filterVO0 = new FilterVO();
      Interval interval0 = filterVO0.getTimeInterval();
      assertNull(interval0);
  }
}
