/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 13 00:43:26 GMT 2022
 */

package org.remast.baralga.repository;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.remast.baralga.repository.ProjectVO;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProjectVO_ESTest extends ProjectVO_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", ";{<a4PDVmX-f<", false);
      boolean boolean0 = projectVO0.isActive();
      assertEquals(";{<a4PDVmX-f<", projectVO0.getDescription());
      assertEquals("", projectVO0.getId());
      assertFalse(boolean0);
      assertEquals("", projectVO0.getTitle());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", (String) null, "", true);
      String string0 = projectVO0.getTitle();
      assertNull(string0);
      assertTrue(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", "", true);
      projectVO0.setTitle(".BCd+xGZ");
      projectVO0.getTitle();
      assertTrue(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("vU;>X(K`i_{", "vU;>X(K`i_{", "vU;>X(K`i_{", false);
      projectVO0.setId((String) null);
      projectVO0.getId();
      assertFalse(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", ";{<a4PDVmX-f<", false);
      assertEquals("", projectVO0.getId());
      
      projectVO0.setId(":jtP_rli%d8");
      projectVO0.getId();
      assertEquals("", projectVO0.getTitle());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", ";{<a4PDVmX-f<", false);
      assertEquals(";{<a4PDVmX-f<", projectVO0.getDescription());
      
      projectVO0.setDescription((String) null);
      projectVO0.getDescription();
      assertEquals("", projectVO0.getTitle());
      assertEquals("", projectVO0.getId());
      assertFalse(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", ";{<a4PDVmX-f<", false);
      String string0 = projectVO0.getDescription();
      assertFalse(projectVO0.isActive());
      assertEquals(";{<a4PDVmX-f<", string0);
      assertEquals("", projectVO0.getTitle());
      assertEquals("", projectVO0.getId());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", "", true);
      projectVO0.getTitle();
      assertTrue(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", "", true);
      projectVO0.getDescription();
      assertTrue(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", "", true);
      projectVO0.getId();
      assertTrue(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", "", true);
      boolean boolean0 = projectVO0.isActive();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", "", true);
      assertTrue(projectVO0.isActive());
      
      projectVO0.setActive(false);
      assertFalse(projectVO0.isActive());
  }
}
