/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 13 00:43:12 GMT 2022
 */

package org.remast.baralga.repository;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.remast.baralga.repository.UnauthorizedException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UnauthorizedException_ESTest extends UnauthorizedException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UnauthorizedException unauthorizedException0 = new UnauthorizedException((String) null);
      String string0 = unauthorizedException0.getUser();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UnauthorizedException unauthorizedException0 = new UnauthorizedException("97W4");
      String string0 = unauthorizedException0.getUser();
      assertEquals("97W4", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UnauthorizedException unauthorizedException0 = new UnauthorizedException("");
      String string0 = unauthorizedException0.getUser();
      assertEquals("", string0);
  }
}
