/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 17 12:38:27 GMT 2022
 */

package org.remast.baralga.repository;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.joda.time.DateTimeZone;
import org.joda.time.Interval;
import org.joda.time.MutableInterval;
import org.joda.time.YearMonth;
import org.junit.runner.RunWith;
import org.remast.baralga.repository.FilterVO;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FilterVO_ESTest extends FilterVO_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FilterVO filterVO0 = new FilterVO();
      Interval interval0 = new Interval(0L, 0L);
      filterVO0.setTimeInterval(interval0);
      Interval interval1 = filterVO0.getTimeInterval();
      assertEquals(0L, interval1.getEndMillis());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FilterVO filterVO0 = new FilterVO();
      MutableInterval mutableInterval0 = new MutableInterval((-1612L), (-1505L));
      Interval interval0 = mutableInterval0.toInterval();
      filterVO0.setTimeInterval(interval0);
      Interval interval1 = filterVO0.getTimeInterval();
      assertEquals((-1612L), interval1.getStartMillis());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FilterVO filterVO0 = new FilterVO();
      DateTimeZone dateTimeZone0 = DateTimeZone.UTC;
      YearMonth yearMonth0 = new YearMonth(dateTimeZone0);
      Interval interval0 = yearMonth0.toInterval();
      filterVO0.setTimeInterval(interval0);
      Interval interval1 = filterVO0.getTimeInterval();
      assertSame(interval1, interval0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FilterVO filterVO0 = new FilterVO();
      Interval interval0 = filterVO0.getTimeInterval();
      assertNull(interval0);
  }
}
