/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 17 12:36:25 GMT 2022
 */

package org.remast.baralga.repository;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.remast.baralga.repository.ProjectVO;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProjectVO_ESTest extends ProjectVO_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("2x\"5z'_4Q", "2x\"5z'_4Q", "2x\"5z'_4Q", true);
      assertTrue(projectVO0.isActive());
      
      projectVO0.setActive(false);
      boolean boolean0 = projectVO0.isActive();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("2x\"5z'_4Q", "2x\"5z'_4Q", "2x\"5z'_4Q", true);
      projectVO0.getTitle();
      assertTrue(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", "Ed~\nCl1", true);
      String string0 = projectVO0.getTitle();
      assertTrue(projectVO0.isActive());
      assertEquals("Ed~\nCl1", projectVO0.getDescription());
      assertEquals("", string0);
      assertEquals("", projectVO0.getId());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("2x\"5z'_4Q", "2x\"5z'_4Q", "2x\"5z'_4Q", true);
      projectVO0.setId((String) null);
      projectVO0.getId();
      assertTrue(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("2x\"5z'_4Q", "2x\"5z'_4Q", "2x\"5z'_4Q", true);
      projectVO0.setId("");
      projectVO0.getId();
      assertTrue(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", "Ed~\nCl1", true);
      assertEquals("Ed~\nCl1", projectVO0.getDescription());
      
      projectVO0.setDescription((String) null);
      projectVO0.getDescription();
      assertTrue(projectVO0.isActive());
      assertEquals("", projectVO0.getTitle());
      assertEquals("", projectVO0.getId());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("Vq,U~`kKY~`<T2)`lt", "", "%DuqQHdtB->fqQDcD", false);
      assertEquals("%DuqQHdtB->fqQDcD", projectVO0.getDescription());
      
      projectVO0.setDescription("");
      projectVO0.getDescription();
      assertFalse(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO((String) null, (String) null, "ZN4g=).u\"gS^);xH7Yy", true);
      String string0 = projectVO0.getTitle();
      assertNull(string0);
      assertTrue(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO((String) null, (String) null, "ZN4g=).u\"gS^);xH7Yy", true);
      String string0 = projectVO0.getDescription();
      assertTrue(projectVO0.isActive());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("2x\"5z'_4Q", "2x\"5z'_4Q", "2x\"5z'_4Q", true);
      projectVO0.getId();
      assertTrue(projectVO0.isActive());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("2x\"5z'_4Q", "2x\"5z'_4Q", "2x\"5z'_4Q", true);
      boolean boolean0 = projectVO0.isActive();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ProjectVO projectVO0 = new ProjectVO("", "", "Ed~\nCl1", true);
      assertEquals("", projectVO0.getTitle());
      
      projectVO0.setTitle("Ed~\nCl1");
      assertEquals("Ed~\nCl1", projectVO0.getDescription());
  }
}
